### ISSUE TITLE
integer out of range for 'I' format code

### ISSUE THREAD

**Issue by nanodan** [eight04/pyAPNG#3]
Whenever I try to use this I get the error code `integer out of range for 'I' format code`

e.g.

APNG.from_files(images, delay=100).save('test.png')

Where images is a list of filepaths returns this error.

Python 2.7

**Comment by eight04** [comment]
This is probably due to:

> Changed in version 3.0: The result is always unsigned. To generate the same numeric value across all Python versions and platforms, use crc32(data) & 0xffffffff.

https://docs.python.org/3.6/library/binascii.html#binascii.crc32

A solution:

* https://github.com/juricap/pyAPNG/commit/c7163a0b9e712be8159457b1aaff07e0dc89857a

However, this module is written in Python 3.5 and I didn't test it in Python 2. If you like to make it compatible with Py2, feel free to open a PR.

**Comment by nanodan** [comment]
Yeah sounds good, it does work fine in Python 3.5. I'll take a look and see if I can make it Python 2 compatible as well.

**Comment by eight04** [comment]
Fixed in 0.3.0.
